### PR TITLE
Remove redundant step from workflow example

### PR DESCRIPTION
**Pull request by pindab0ter**
The workflow [runs fine without](https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/actions/runs/12027387246) it as you can see in [this repo](https://github.com/pindab0ter/UPSFriendlyNixieTubeDisplay/blob/548d634da9b89b1e68cdc9dfaaa959c0712700d0/.github/workflows/publish.yml)

### CODE REVIEW

**Comment by TheBrutalX** [comment]
Hi,
into a pubblic runner of GH with prebuild image is redundant, in a custom runner i think is better to have this step

**Comment by TheBrutalX** [comment]
These days I will have to do a clean install of debian and ubuntu-server 22.04, if none of this system needs this step, I will remove it.

**Comment by TheBrutalX** [comment]
Hi,
I tested the pipeline in a clean VM without the node section and you are right, thanks for your input.

---
The executions
**Debian 12 minimal** [log](https://github.com/TheBrutalX/Factorio-Test-Mod/actions/runs/12057115857/job/33621039152)
**Ubuntu Server 22.04 Minimal** [log](https://github.com/TheBrutalX/Factorio-Test-Mod/actions/runs/12057286205/job/33621579807)

**Comment by pindab0ter** [comment]
You're welcome! Glad I could be of help.

**Pull request merged**
